server:  
  servlet:
   context-path: /liare
  port : 8092


# ===============================
# = DATA SOURCE ORACLE
# ===============================

#configuracion oracle basica
spring:         
    datasource :
     url: jdbc:oracle:thin:@localhost:1521/YASMIN
     username: system
     password: crunch
     #password: ENC(9VAtHoXvKpjgYlBEEgAuhKygNit1TTbR) 
     driver-class-name: oracle.jdbc.driver.OracleDriver
     #recomendado y probado para jboss   
     hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
     
     #hibernate config
    jpa:
      database-platform: org.hibernate.dialect.Oracle10gDialect
      show-sql: true  
    #Recomendado para jboss                    
    #jmx
      #default-domain: test
      #enabled: false


# ===============================
# = Thymeleaf configurations
# =============================== 
    thymeleaf:
      cache: false
      check-template: true
      check-template-location: true     
      servlet:
        content-type:  text/html 
      enabled: true
      encoding: UTF-8
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
      # excluded-view-names:
      # template-resolver-order:
      # view-names:          
      
#CONTENT TYPES
    mvc:
     contentnegotiation:
      favor-parameter : true
      media-types:
       pdf  : application/pdf
       xlsx : application/vnd.openxmlformats-officedocument.spreadsheetml.sheet      
       xml  : application/xml
       json : application/json      
       
       
#SUBIDA DE ARCHIVOS
    servlet:
      multipart.max-file-size : 11MB
      multipart.max-request-size : 11MB
  
#No olvidar esto    
multipart:
        maxFileSize: -1     
       
       


#ENCRITAR DATOS SENSIBLES  
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: mininterpasswordsecret2019$

#CONFIGURAR DE LOS LOGS POR DEFAULT EL FILE MAX SIZE SON 10MB       
logging:
  level:
    root: INFO
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: debug
    
    